export const TEXTS = {
  profileTitle: 'Mon profil',
  defaultUser: 'Utilisateur',
  noEmail: 'Adresse e-mail non disponible',
  settings: 'Paramètres',
  stats: 'Mes statistiques',
  appearance: 'Apparence',
  homeAddMeal: 'Ajouter un repas',
  homeScanProduct: 'Scanner un produit',
  homeRecentMeals: 'Mes repas récents',
  homeWeeklyTracking: 'Suivi hebdomadaire',
  homeDailyAverage: 'Moyenne journalière : 1850 kcal',
  addMeal: 'Ajouter à mon repas',
  validateMeal: 'Valider le repas',
  scanBarcode: 'Scanner un Code Barres',
  noFoodFound: 'Aucun aliment trouvé.',
  noMealAdded: 'Aucun aliment ajouté.',
  searchPlaceholder: 'Rechercher un aliment',
  scanAnother: 'Scannez un autre code ?',
  reset: 'Réinitialiser',
  cameraPermission: 'Permission caméra requise',
  allowCamera: 'Autoriser la caméra',
  loading: 'Chargement...',
  error: 'Erreur',
  noData: 'Aucune donnée trouvée.',
  back: '< Retour',
  addMealTitle: 'Ajouter un repas',
  mealSaved: 'Repas enregistré !',
  noResults: 'Aucun aliment trouvé.',
  addedFoodsTitle: 'Aliments ajoutés au repas',
};
