import { StyleSheet } from 'react-native';

export const styles = StyleSheet.create({
    card: {
        backgroundColor: 'linear-gradient(135deg, #A5D6A7 0%, #FFF176 100%)',
        borderRadius: 24,
        padding: 22,
        marginVertical: 14,
        marginHorizontal: 16,
        shadowColor: '#A5D6A7',
        shadowOpacity: 0.12,
        shadowRadius: 12,
        shadowOffset: { width: 0, height: 6 },
        elevation: 6,
        flexDirection: 'row',
        alignItems: 'center',
    },
    leftIcon: {
        width: 54,
        height: 54,
        borderRadius: 27,
        backgroundColor: '#fff',
        marginRight: 18,
        justifyContent: 'center',
        alignItems: 'center',
        shadowColor: '#A5D6A7',
        shadowOpacity: 0.18,
        shadowRadius: 8,
        shadowOffset: { width: 0, height: 2 },
    },
    content: {
        flex: 1,
    },
    title: {
        fontSize: 20,
        fontWeight: 'bold',
        color: '#388E3C',
        marginBottom: 4,
    },
    calories: {
        fontSize: 16,
        color: '#333',
        marginBottom: 8,
        fontWeight: '500',
    },
    link: {
        fontSize: 15,
        color: '#FFB300',
        textDecorationLine: 'underline',
        marginTop: 4,
        fontWeight: '500',
        alignSelf: 'flex-start',
    },
    favBtn: {
        marginLeft: 12,
        padding: 8,
        borderRadius: 20,
        backgroundColor: '#fff',
        shadowColor: '#FFB300',
        shadowOpacity: 0.15,
        shadowRadius: 6,
        shadowOffset: { width: 0, height: 2 },
    },
    emptyContainer: {
        flex: 1,
        justifyContent: 'center',
        alignItems: 'center',
        padding: 32,
    },
    emptyText: {
        fontSize: 18,
        color: '#888',
        textAlign: 'center',
        fontWeight: '500',
    },
});
